apiVersion: 1

contactPoints:
  - orgId: 1
    name: default-contact
    receivers:
      - uid: default-null-receiver
        type: grafana-default-email
        settings:
          addresses: admin@localhost
        disableResolveMessage: false

policies:
  - orgId: 1
    receiver: default-contact
    group_by: [alertname, application]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 1h